version: '3.1'
services:
  app:
    container_name: springboot
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/turbo_goods
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - postgresqldb

  postgresqldb:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=admin
      - POSTGRES_DB=turbo_goods

volumes:
  pgdata:
